services:

  postgres_db:
    image: postgres:alpine3.17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-applicant}
      POSTGRES_PASSWORD: ${DB_PASS:-temp123}
      POSTGRES_DB: ${DB_NAME:-blog_db}
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:6.21
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres_db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: pass
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    logging:
      driver: none
